"""100-asset catalog for V3 reliability stress test.
Distribution: 40 GLB, 30 FBX, 30 OBJ
Each entry: source, name, url, file_filter, fmt
"""

ASSETS_V3 = [

    # ── GLB assets (40) ──────────────────────────────────────────────────────
    # Kenney 3D Platformer (1 archive, many GLB)
    {"source":"Kenney","name":"Platformer Character","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"character.glb"},
    {"source":"Kenney","name":"Platformer Coin","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"coin.glb"},
    {"source":"Kenney","name":"Platformer Gem","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"gem.glb"},
    {"source":"Kenney","name":"Platformer Platform A","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"platform-a.glb"},
    {"source":"Kenney","name":"Platformer Platform B","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"platform-b.glb"},
    {"source":"Kenney","name":"Platformer Platform C","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"platform-c.glb"},
    {"source":"Kenney","name":"Platformer Flag","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"flag.glb"},
    {"source":"Kenney","name":"Platformer Spring","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-3D-Platformer/archive/refs/heads/main.zip",
     "file_filter":"spring.glb"},

    # Kenney City Builder
    {"source":"Kenney","name":"City Garage","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-garage.glb"},
    {"source":"Kenney","name":"City Building Small C","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-small-c.glb"},
    {"source":"Kenney","name":"City Building Small A","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-small-a.glb"},
    {"source":"Kenney","name":"City Building Small B","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-small-b.glb"},
    {"source":"Kenney","name":"City Building Large A","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-large-a.glb"},
    {"source":"Kenney","name":"City Building Large B","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"building-large-b.glb"},
    {"source":"Kenney","name":"City Road Straight","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"road-straight.glb"},
    {"source":"Kenney","name":"City Road Corner","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"road-corner.glb"},
    {"source":"Kenney","name":"City Tree Large","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"nature-tree-large.glb"},
    {"source":"Kenney","name":"City Tree Small","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-City-Builder/archive/refs/heads/main.zip",
     "file_filter":"nature-tree-small.glb"},

    # Kenney FPS Kit
    {"source":"Kenney","name":"FPS Blaster","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"blaster.glb"},
    {"source":"Kenney","name":"FPS Bullet","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"bullet.glb"},
    {"source":"Kenney","name":"FPS Wall","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"wall.glb"},
    {"source":"Kenney","name":"FPS Floor","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"floor.glb"},
    {"source":"Kenney","name":"FPS Door","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"door.glb"},
    {"source":"Kenney","name":"FPS Target","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"target.glb"},
    {"source":"Kenney","name":"FPS Crate","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"crate.glb"},
    {"source":"Kenney","name":"FPS Barrel","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"barrel.glb"},
    {"source":"Kenney","name":"FPS Stairs","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"stairs.glb"},
    {"source":"Kenney","name":"FPS Ramp","fmt":"glb",
     "url":"https://github.com/KenneyNL/Starter-Kit-FPS/archive/refs/heads/main.zip",
     "file_filter":"ramp.glb"},

    # GLTF Sample Models (from Khronos gltf-Sample-Models)
    {"source":"KhronosSamples","name":"Box GLTF","fmt":"gltf",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"Box.gltf"},
    {"source":"KhronosSamples","name":"BoxTextured GLTF","fmt":"gltf",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"BoxTextured.gltf"},
    {"source":"KhronosSamples","name":"Duck GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"Duck.glb"},
    {"source":"KhronosSamples","name":"Avocado GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"Avocado.glb"},
    {"source":"KhronosSamples","name":"BarramundiFish GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"BarramundiFish.glb"},
    {"source":"KhronosSamples","name":"BoomBox GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"BoomBox.glb"},
    {"source":"KhronosSamples","name":"Corset GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"Corset.glb"},
    {"source":"KhronosSamples","name":"DamagedHelmet GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"DamagedHelmet.glb"},
    {"source":"KhronosSamples","name":"FlightHelmet GLTF","fmt":"gltf",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"FlightHelmet.gltf"},
    {"source":"KhronosSamples","name":"Lantern GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"Lantern.glb"},
    {"source":"KhronosSamples","name":"SciFiHelmet GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"SciFiHelmet.gltf"},
    {"source":"KhronosSamples","name":"WaterBottle GLB","fmt":"glb",
     "url":"https://github.com/KhronosGroup/glTF-Sample-Models/archive/refs/heads/main.zip",
     "file_filter":"WaterBottle.glb"},

    # ── FBX assets (30) ──────────────────────────────────────────────────────
    {"source":"Quaternius","name":"FBX Female","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"ultimate-modular-women.fbx"},
    {"source":"Quaternius","name":"FBX AC","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"AC.fbx"},
    {"source":"Quaternius","name":"FBX Computer","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Computer.fbx"},
    {"source":"Quaternius","name":"FBX Door","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Door.fbx"},
    {"source":"Quaternius","name":"FBX Fence","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Fence.fbx"},
    {"source":"Quaternius","name":"FBX Chair","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Chair.fbx"},
    {"source":"Quaternius","name":"FBX Couch","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Couch.fbx"},
    {"source":"Quaternius","name":"FBX Desk","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Desk.fbx"},
    {"source":"Quaternius","name":"FBX Drawer","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Drawer.fbx"},
    {"source":"Quaternius","name":"FBX Fridge","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Fridge.fbx"},
    {"source":"Quaternius","name":"FBX Lamp","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Lamp.fbx"},
    {"source":"Quaternius","name":"FBX Monitor","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Monitor.fbx"},
    {"source":"Quaternius","name":"FBX Shelf","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Shelf.fbx"},
    {"source":"Quaternius","name":"FBX Table","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Table.fbx"},
    {"source":"Quaternius","name":"FBX TV","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"TV.fbx"},
    {"source":"Quaternius","name":"FBX Toilet","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Toilet.fbx"},
    {"source":"Quaternius","name":"FBX Bathtub","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Bathtub.fbx"},
    {"source":"Quaternius","name":"FBX Sink","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Sink.fbx"},
    {"source":"Quaternius","name":"FBX Oven","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Oven.fbx"},
    {"source":"Quaternius","name":"FBX Microwave","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Microwave.fbx"},
    {"source":"Quaternius","name":"FBX Blender","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Blender.fbx"},
    {"source":"Quaternius","name":"FBX Toaster","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Toaster.fbx"},
    {"source":"Quaternius","name":"FBX Kettle","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Kettle.fbx"},
    {"source":"Quaternius","name":"FBX Bed","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Bed.fbx"},
    {"source":"Quaternius","name":"FBX Wardrobe","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Wardrobe.fbx"},
    {"source":"Quaternius","name":"FBX Bookcase","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Bookcase.fbx"},
    {"source":"Quaternius","name":"FBX Fireplace","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Fireplace.fbx"},
    {"source":"Quaternius","name":"FBX Vase","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Vase.fbx"},
    {"source":"Quaternius","name":"FBX Clock","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Clock.fbx"},
    {"source":"Quaternius","name":"FBX Plant","fmt":"fbx",
     "url":"https://github.com/V-Sekai-fire/TEST_fbx_quaternius/archive/refs/heads/main.zip",
     "file_filter":"Plant.fbx"},

    # ── OBJ assets (30) ──────────────────────────────────────────────────────
    # Recast Navigation (navmesh samples)
    {"source":"OpenGameArt","name":"OBJ Human","fmt":"obj",
     "url":"https://github.com/cdgramos/OpenGL-Object-Importer-Library/archive/refs/heads/master.zip",
     "file_filter":"human.obj"},
    {"source":"OpenGameArt","name":"OBJ Dungeon","fmt":"obj",
     "url":"https://github.com/recastnavigation/recastnavigation/archive/refs/heads/master.zip",
     "file_filter":"dungeon.obj"},
    {"source":"OpenGameArt","name":"OBJ Nav Test","fmt":"obj",
     "url":"https://github.com/recastnavigation/recastnavigation/archive/refs/heads/master.zip",
     "file_filter":"nav_test.obj"},
    {"source":"OpenGameArt","name":"OBJ African Head","fmt":"obj",
     "url":"https://github.com/ssloy/tinyrenderer/archive/refs/heads/master.zip",
     "file_filter":"african_head.obj"},
    {"source":"OpenGameArt","name":"OBJ Diablo3 Pose","fmt":"obj",
     "url":"https://github.com/ssloy/tinyrenderer/archive/refs/heads/master.zip",
     "file_filter":"diablo3_pose.obj"},
    # tinyrenderer obj models
    {"source":"Tinyrenderer","name":"OBJ Boggie Body","fmt":"obj",
     "url":"https://github.com/ssloy/tinyrenderer/archive/refs/heads/master.zip",
     "file_filter":"boggie_body.obj"},
    {"source":"Tinyrenderer","name":"OBJ Boggie Eyes","fmt":"obj",
     "url":"https://github.com/ssloy/tinyrenderer/archive/refs/heads/master.zip",
     "file_filter":"boggie_eyes.obj"},
    {"source":"Tinyrenderer","name":"OBJ Boggie Head","fmt":"obj",
     "url":"https://github.com/ssloy/tinyrenderer/archive/refs/heads/master.zip",
     "file_filter":"boggie_head.obj"},
    # Cornell Box / McGuire CG Archive OBJ models
    {"source":"McGuire","name":"OBJ Fireplace Room","fmt":"obj",
     "url":"https://github.com/McGuirePrograms/smallpaint/archive/refs/heads/master.zip",
     "file_filter":"room.obj"},
    {"source":"McGuire","name":"OBJ Cornell Box","fmt":"obj",
     "url":"https://github.com/McGuirePrograms/smallpaint/archive/refs/heads/master.zip",
     "file_filter":"cornell_box.obj"},
    # Three.js sample OBJ models
    {"source":"ThreeJS","name":"OBJ Monkey","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"monkey.obj"},
    {"source":"ThreeJS","name":"OBJ Male02","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"male02.obj"},
    {"source":"ThreeJS","name":"OBJ Female02","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"female02.obj"},
    {"source":"ThreeJS","name":"OBJ Windmill","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"windmill.obj"},
    {"source":"ThreeJS","name":"OBJ Chest","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"chest.obj"},
    {"source":"ThreeJS","name":"OBJ Flamingo","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"flamingo.obj"},
    {"source":"ThreeJS","name":"OBJ Parrot","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"parrot.obj"},
    {"source":"ThreeJS","name":"OBJ Stork","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"stork.obj"},
    {"source":"ThreeJS","name":"OBJ Horse","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"horse.obj"},
    {"source":"ThreeJS","name":"OBJ Skull","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"skull.obj"},
    {"source":"ThreeJS","name":"OBJ Ninja","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"ninja.obj"},
    {"source":"ThreeJS","name":"OBJ Cerberus","fmt":"obj",
     "url":"https://github.com/mrdoob/three.js/archive/refs/heads/dev.zip",
     "file_filter":"Cerberus.obj"},
    # stanford models (bunny/dragon commonly redistributed)
    {"source":"StanfordModels","name":"OBJ Bunny","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"bunny.obj"},
    {"source":"StanfordModels","name":"OBJ Armadillo","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"armadillo.obj"},
    {"source":"StanfordModels","name":"OBJ Spot Cow","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"spot.obj"},
    {"source":"StanfordModels","name":"OBJ Suzanne","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"suzanne.obj"},
    {"source":"StanfordModels","name":"OBJ Cylinder","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"cylinder.obj"},
    {"source":"StanfordModels","name":"OBJ Fertility","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"fertility.obj"},
    {"source":"StanfordModels","name":"OBJ Decimated Knight","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"decimated-knight.obj"},
    {"source":"StanfordModels","name":"OBJ Cheburashka","fmt":"obj",
     "url":"https://github.com/alecjacobson/common-3d-test-models/archive/refs/heads/master.zip",
     "file_filter":"cheburashka.obj"},
]

_glb = sum(1 for a in ASSETS_V3 if a["fmt"] in ("glb", "gltf"))
_fbx = sum(1 for a in ASSETS_V3 if a["fmt"] == "fbx")
_obj = sum(1 for a in ASSETS_V3 if a["fmt"] == "obj")
assert len(ASSETS_V3) == 100, f"Expected 100 assets, got {len(ASSETS_V3)} (glb={_glb} fbx={_fbx} obj={_obj})"
