[Icon Theme]
Name=PyFlare Icons
Comment=PyFlare OS icon theme by Aachman Studios
Inherits=Adwaita,hicolor
Directories=16x16/apps,24x24/apps,32x32/apps,48x48/apps,64x64/apps,128x128/apps,256x256/apps,scalable/apps,16x16/status,48x48/status

[16x16/apps]
Size=16
Type=Fixed
Context=Applications

[24x24/apps]
Size=24
Type=Fixed
Context=Applications

[32x32/apps]
Size=32
Type=Fixed
Context=Applications

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[64x64/apps]
Size=64
Type=Fixed
Context=Applications

[128x128/apps]
Size=128
Type=Fixed
Context=Applications

[256x256/apps]
Size=256
Type=Fixed
Context=Applications

[scalable/apps]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Applications

[16x16/status]
Size=16
Type=Fixed
Context=Status

[48x48/status]
Size=48
Type=Fixed
Context=Status
