# PyFlare GDM3 configuration
# /etc/gdm3/custom.conf

[daemon]
WaylandEnable=true
DefaultSession=gnome

# Automatic login disabled by default (Calamares sets this at install time)
# AutomaticLoginEnable=true
# AutomaticLogin=pyflare

[security]
AllowRoot=false

[xdmcp]
Enable=false

[chooser]
Multicast=false

[debug]
Enable=false
