# PyFlare OS — resource limits
# Increase file descriptor limit for PyFlare Engine
pyflare    soft    nofile    65536
pyflare    hard    nofile    131072
pyflare    soft    nproc     32768
pyflare    hard    nproc     65536
# Developers
@sudo      soft    nofile    32768
@sudo      hard    nofile    65536
